on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Swift 5.4
            xcode: /Applications/Xcode_12.5.1.app
          - name: Swift 5.5
            xcode: /Applications/Xcode_13.2.1.app
    
    name: Build and Test (${{ matrix.name }})
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Switch Xcode version
        run: sudo xcode-select --switch ${{ matrix.xcode }}
      - name: Generate xcodeproj
        run: swift package generate-xcodeproj
      - name: Test
        run: xcodebuild clean test -project Request.xcodeproj -scheme "Request-Package" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet -enableCodeCoverage YES -derivedDataPath .build/derivedData
      - name: Upload Codecov report
        run: bash <(curl -s https://codecov.io/bash) -D .build/derivedData
