name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
      with:
        swift-version: "5.4"
    - uses: actions/checkout@v2
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Test
      run: xcodebuild clean test -project Request.xcodeproj -scheme "Request-Package" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet -enableCodeCoverage YES -derivedDataPath .build/derivedData
    - name: Upload Codecov report
      run: bash <(curl -s https://codecov.io/bash) -D .build/derivedData
